# Generated by Django 6.0.7 on 2026-07-10 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('odometer', models.PositiveIntegerField(help_text='Kilometres')),
                ('litres', models.DecimalField(decimal_places=2, max_digits=7)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('full_tank', models.BooleanField(default=True)),
                ('station', models.CharField(blank=True, max_length=120)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_entries', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name_plural': 'fuel entries',
                'ordering': ['-date', '-odometer'],
            },
        ),
        migrations.CreateModel(
            name='RunningLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('odometer', models.PositiveIntegerField(help_text='Kilometres')),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='running_logs', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-date', '-odometer'],
            },
        ),
    ]
