# Generated by Django 6.0.7 on 2026-07-10 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('document_expiry', 'Document expiry'), ('service_due', 'Service due')], default='manual', max_length=20)),
                ('trigger_type', models.CharField(choices=[('date', 'Date'), ('odometer', 'Odometer')], default='date', max_length=10)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('due_odometer', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('done', 'Done'), ('dismissed', 'Dismissed')], default='open', max_length=10)),
                ('note', models.TextField(blank=True)),
                ('dedupe_key', models.CharField(blank=True, max_length=120, null=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['due_date', 'due_odometer', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('vehicle', 'dedupe_key'), name='unique_vehicle_dedupe_key')],
            },
        ),
    ]
