# Generated by Django 6.0.7 on 2026-07-10 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotspot_key', models.CharField(help_text='Matches a 3D hotspot position in the frontend layout.', max_length=40)),
                ('label', models.CharField(max_length=80)),
                ('category', models.CharField(choices=[('tyre', 'Tyre'), ('engine', 'Engine'), ('brakes', 'Brakes'), ('battery', 'Battery'), ('oil', 'Oil'), ('other', 'Other')], default='other', max_length=12)),
                ('health', models.CharField(choices=[('good', 'Good'), ('warning', 'Attention soon'), ('critical', 'Action needed')], default='good', max_length=10)),
                ('last_serviced_date', models.DateField(blank=True, null=True)),
                ('last_serviced_odometer', models.PositiveIntegerField(blank=True, null=True)),
                ('expected_life_km', models.PositiveIntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['hotspot_key'],
                'constraints': [models.UniqueConstraint(fields=('vehicle', 'hotspot_key'), name='unique_vehicle_hotspot_key')],
            },
        ),
    ]
