# Generated by Django 6.0.7 on 2026-07-10 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('odometer', models.PositiveIntegerField(blank=True, help_text='Kilometres', null=True)),
                ('category', models.CharField(choices=[('oil_change', 'Oil change'), ('tyres', 'Tyres'), ('brakes', 'Brakes'), ('battery', 'Battery'), ('service', 'General service'), ('repair', 'Repair'), ('other', 'Other')], default='service', max_length=20)),
                ('title', models.CharField(max_length=160)),
                ('parts_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vendor', models.CharField(blank=True, max_length=120)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('next_due_odometer', models.PositiveIntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-date', '-odometer'],
            },
        ),
    ]
