# Generated by Django 6.0.7 on 2026-07-10 05:29

import apps.documents.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('insurance', 'Insurance'), ('registration', 'Registration'), ('license', 'License'), ('warranty', 'Warranty'), ('inspection', 'Inspection'), ('invoice', 'Invoice'), ('manual', 'Manual'), ('other', 'Other')], default='other', max_length=20)),
                ('title', models.CharField(max_length=160)),
                ('file', models.FileField(upload_to=apps.documents.models.document_upload_path)),
                ('issuer', models.CharField(blank=True, max_length=120)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('policy_number', models.CharField(blank=True, max_length=80)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
